ALTER TABLE "public"."Cve" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Component" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."CpeCandidate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."AuditEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ImportJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ImportStageRow" ENABLE ROW LEVEL SECURITY;
